apiVersion: v1
data:
  template: |
    {
        "declaration": {
            "test": {
                "Shared": {
                    "https_ose_vserver": {
                        "snat": {
                            "bigip": "/Common/RD_000_SNATPOOL_GENERIC"
                        }
                    }
                }
            }
        }
    }
kind: ConfigMap
metadata:
  labels:
    f5type: virtual-server
    overrideAS3: "true"
  name: example-snat
  namespace: default
