apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-app: example_simple_http_application_01
    cis.f5.com/as3-pool: web_pool
    cis.f5.com/as3-tenant: example_simple_http_application
  name: example-simple-http-application-01
  namespace: default
spec:
  ports:
  - name: example-simple-http-application-01-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example-simple-http-application-01
  type: NodePort
