apiVersion: v1
kind: Route
metadata:
  labels:
    name: svc-1
    f5type: systest
  name: svc1-route-unsecured
  namespace: default
  annotations:
spec:
  host: foo3.com
  path: "/test"
  port:
    targetPort: 80
  to:
    kind: Service
    name: svc-1
